; COLORS
;==================================================================== 
; Theme             foreground  background  broderbg

; Tokyonight        #a9b1d6     #1a1b26     #7da6ff
; Kanagawa          #dcd7ba     #1f1f28     #c8c093
; Kanagawa Wave     #dcd7ba     #16161d     #7fb4ca n #2d4f67
; Catppuccin        #cdd6f4     #1e1e2e     #cba6f7
; Ethereal          #ffcead     #060b1e     #f7dc9c
; Ristretto         #e2d5d6     #2c2524     #ddd0d1
; Matte black       #bebebe     #121212     #e68e0d
;
; light themes
; Catppuccin Latte  #4c4f69     #eff1f5     #8839ef or #dc8a78
; Kangawava Lotus   #545464     #f2ecbc     #43436c
;====================================================================
[colors]
foreground = #bebebe
background = #121212
highlight = #e68e0d
red = #ff0000
cool = #74c7ec
hot = #EE4B2B
charging = #70e83b
full = #09e807
